// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.1
//
// <auto-generated>
//
// Generated from file `Message.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.rain.ice.message;

public final class MessageServicePrxHelper extends Ice.ObjectPrxHelperBase implements MessageServicePrx
{
    private static final String __doInvoke_name = "doInvoke";

    public String doInvoke(MsgRequest msgRequest)
    {
        return doInvoke(msgRequest, null, false);
    }

    public String doInvoke(MsgRequest msgRequest, java.util.Map<String, String> __ctx)
    {
        return doInvoke(msgRequest, __ctx, true);
    }

    private String doInvoke(MsgRequest msgRequest, java.util.Map<String, String> __ctx, boolean __explicitCtx)
    {
        __checkTwowayOnly(__doInvoke_name);
        return end_doInvoke(begin_doInvoke(msgRequest, __ctx, __explicitCtx, true, null));
    }

    public Ice.AsyncResult begin_doInvoke(MsgRequest msgRequest)
    {
        return begin_doInvoke(msgRequest, null, false, false, null);
    }

    public Ice.AsyncResult begin_doInvoke(MsgRequest msgRequest, java.util.Map<String, String> __ctx)
    {
        return begin_doInvoke(msgRequest, __ctx, true, false, null);
    }

    public Ice.AsyncResult begin_doInvoke(MsgRequest msgRequest, Ice.Callback __cb)
    {
        return begin_doInvoke(msgRequest, null, false, false, __cb);
    }

    public Ice.AsyncResult begin_doInvoke(MsgRequest msgRequest, java.util.Map<String, String> __ctx, Ice.Callback __cb)
    {
        return begin_doInvoke(msgRequest, __ctx, true, false, __cb);
    }

    public Ice.AsyncResult begin_doInvoke(MsgRequest msgRequest, Callback_MessageService_doInvoke __cb)
    {
        return begin_doInvoke(msgRequest, null, false, false, __cb);
    }

    public Ice.AsyncResult begin_doInvoke(MsgRequest msgRequest, java.util.Map<String, String> __ctx, Callback_MessageService_doInvoke __cb)
    {
        return begin_doInvoke(msgRequest, __ctx, true, false, __cb);
    }

    public Ice.AsyncResult begin_doInvoke(MsgRequest msgRequest, 
                                          IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                          IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb)
    {
        return begin_doInvoke(msgRequest, null, false, false, __responseCb, __exceptionCb, null);
    }

    public Ice.AsyncResult begin_doInvoke(MsgRequest msgRequest, 
                                          IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                          IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                          IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_doInvoke(msgRequest, null, false, false, __responseCb, __exceptionCb, __sentCb);
    }

    public Ice.AsyncResult begin_doInvoke(MsgRequest msgRequest, 
                                          java.util.Map<String, String> __ctx, 
                                          IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                          IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb)
    {
        return begin_doInvoke(msgRequest, __ctx, true, false, __responseCb, __exceptionCb, null);
    }

    public Ice.AsyncResult begin_doInvoke(MsgRequest msgRequest, 
                                          java.util.Map<String, String> __ctx, 
                                          IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                          IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                          IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_doInvoke(msgRequest, __ctx, true, false, __responseCb, __exceptionCb, __sentCb);
    }

    private Ice.AsyncResult begin_doInvoke(MsgRequest msgRequest, 
                                           java.util.Map<String, String> __ctx, 
                                           boolean __explicitCtx, 
                                           boolean __synchronous, 
                                           IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                           IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                           IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_doInvoke(msgRequest, __ctx, __explicitCtx, __synchronous, 
                              new IceInternal.Functional_TwowayCallbackArg1<String>(__responseCb, __exceptionCb, __sentCb)
                                  {
                                      public final void __completed(Ice.AsyncResult __result)
                                      {
                                          MessageServicePrxHelper.__doInvoke_completed(this, __result);
                                      }
                                  });
    }

    private Ice.AsyncResult begin_doInvoke(MsgRequest msgRequest, 
                                           java.util.Map<String, String> __ctx, 
                                           boolean __explicitCtx, 
                                           boolean __synchronous, 
                                           IceInternal.CallbackBase __cb)
    {
        __checkAsyncTwowayOnly(__doInvoke_name);
        IceInternal.OutgoingAsync __result = getOutgoingAsync(__doInvoke_name, __cb);
        try
        {
            __result.prepare(__doInvoke_name, Ice.OperationMode.Normal, __ctx, __explicitCtx, __synchronous);
            IceInternal.BasicStream __os = __result.startWriteParams(Ice.FormatType.DefaultFormat);
            MsgRequest.__write(__os, msgRequest);
            __result.endWriteParams();
            __result.invoke();
        }
        catch(Ice.Exception __ex)
        {
            __result.abort(__ex);
        }
        return __result;
    }

    public String end_doInvoke(Ice.AsyncResult __iresult)
    {
        IceInternal.OutgoingAsync __result = IceInternal.OutgoingAsync.check(__iresult, this, __doInvoke_name);
        try
        {
            if(!__result.__wait())
            {
                try
                {
                    __result.throwUserException();
                }
                catch(Ice.UserException __ex)
                {
                    throw new Ice.UnknownUserException(__ex.ice_name(), __ex);
                }
            }
            IceInternal.BasicStream __is = __result.startReadParams();
            String __ret;
            __ret = __is.readString();
            __result.endReadParams();
            return __ret;
        }
        finally
        {
            if(__result != null)
            {
                __result.cacheMessageBuffers();
            }
        }
    }

    static public void __doInvoke_completed(Ice.TwowayCallbackArg1<String> __cb, Ice.AsyncResult __result)
    {
        com.rain.ice.message.MessageServicePrx __proxy = (com.rain.ice.message.MessageServicePrx)__result.getProxy();
        String __ret = null;
        try
        {
            __ret = __proxy.end_doInvoke(__result);
        }
        catch(Ice.LocalException __ex)
        {
            __cb.exception(__ex);
            return;
        }
        catch(Ice.SystemException __ex)
        {
            __cb.exception(__ex);
            return;
        }
        __cb.response(__ret);
    }

    public static MessageServicePrx checkedCast(Ice.ObjectPrx __obj)
    {
        return checkedCastImpl(__obj, ice_staticId(), MessageServicePrx.class, MessageServicePrxHelper.class);
    }

    public static MessageServicePrx checkedCast(Ice.ObjectPrx __obj, java.util.Map<String, String> __ctx)
    {
        return checkedCastImpl(__obj, __ctx, ice_staticId(), MessageServicePrx.class, MessageServicePrxHelper.class);
    }

    public static MessageServicePrx checkedCast(Ice.ObjectPrx __obj, String __facet)
    {
        return checkedCastImpl(__obj, __facet, ice_staticId(), MessageServicePrx.class, MessageServicePrxHelper.class);
    }

    public static MessageServicePrx checkedCast(Ice.ObjectPrx __obj, String __facet, java.util.Map<String, String> __ctx)
    {
        return checkedCastImpl(__obj, __facet, __ctx, ice_staticId(), MessageServicePrx.class, MessageServicePrxHelper.class);
    }

    public static MessageServicePrx uncheckedCast(Ice.ObjectPrx __obj)
    {
        return uncheckedCastImpl(__obj, MessageServicePrx.class, MessageServicePrxHelper.class);
    }

    public static MessageServicePrx uncheckedCast(Ice.ObjectPrx __obj, String __facet)
    {
        return uncheckedCastImpl(__obj, __facet, MessageServicePrx.class, MessageServicePrxHelper.class);
    }

    public static final String[] __ids =
    {
        "::Ice::Object",
        "::message::MessageService"
    };

    public static String ice_staticId()
    {
        return __ids[1];
    }

    public static void __write(IceInternal.BasicStream __os, MessageServicePrx v)
    {
        __os.writeProxy(v);
    }

    public static MessageServicePrx __read(IceInternal.BasicStream __is)
    {
        Ice.ObjectPrx proxy = __is.readProxy();
        if(proxy != null)
        {
            MessageServicePrxHelper result = new MessageServicePrxHelper();
            result.__copyFrom(proxy);
            return result;
        }
        return null;
    }

    public static final long serialVersionUID = 0L;
}
