//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.2
//
// <auto-generated>
//
// Generated from file `query.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.yujie.ice.info;

/** @hidden */
public class _QueryEmployeePrxI extends com.zeroc.Ice._ObjectPrxI implements QueryEmployeePrx
{
    /** @hidden */
    public static final long serialVersionUID = 0L;
}
