// **********************************************************************
//
// Copyright (c) 2003-2018 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.5
//
// <auto-generated>
//
// Generated from file `Message.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.rain.common.ice.v1.message;

public interface MessageService extends Ice.Object,
                                        _MessageServiceOperations, _MessageServiceOperationsNC
{
    public static final String ice_staticId = "::message::MessageService";

    public static final long serialVersionUID = 694259936L;
}
