//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.2
//
// <auto-generated>
//
// Generated from file `sms.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.hp.tel.ice.message;

/** @hidden */
public class _SMSServicePrxI extends com.zeroc.Ice._ObjectPrxI implements SMSServicePrx
{
    /** @hidden */
    public static final long serialVersionUID = 0L;
}
