//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.2
//
// <auto-generated>
//
// Generated from file `Message.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.rain.ice.message;

/** @hidden */
public class _MessageServicePrxI extends com.zeroc.Ice._ObjectPrxI implements MessageServicePrx
{
    /** @hidden */
    public static final long serialVersionUID = 0L;
}
