// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.1
//
// <auto-generated>
//
// Generated from file `Message.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.rain.ice.message;

public final class tmapHolder extends Ice.Holder<java.util.Map<java.lang.String, java.lang.String>>
{
    public
    tmapHolder()
    {
    }

    public
    tmapHolder(java.util.Map<java.lang.String, java.lang.String> value)
    {
        super(value);
    }
}
