spring:
  profiles: test
  main:
    banner-mode: off
  datasource:
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 5
    url: jdbc:postgresql://localhost:5432/nev_master?currentSchema=rain
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: rain
        hbm2ddl:
          auto: create


#    initialize: false
#    initialSize: 0
#    timeBetweenEvictionRunsMillis: 5000
#    minEvictableIdleTimeMillis: 5000
#    minIdle: 0

endpoints:
  jmx:
    enabled: true
    unique-names: true
logging:
  pattern:
    console: %d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n
  level: debug

