spring:
  profiles: test
  main:
    banner-mode: off
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.postgresql.Driver
    url: jdbc:mysql://localhost:3307/rain-user?useUnicode=true&characterEncoding=utf8
    username: root
    password: root
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdel: true
    testOnBorrow: false
    testOnReturn: false
    filters: stat,wall,log4j
    logSlowSql: true
    cnnectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
mybatis:
#  type:
#    aliases:
  mapper:
      package:  com.rain.role.mapper
  locations:  classpath*:com/rain/**/mapper/*Mapper.xml

logging:
  level: info
  com.rain: info
