// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.1
//
// <auto-generated>
//
// Generated from file `Message.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.rain.ice.message;

public interface MessageServicePrx extends Ice.ObjectPrx
{
    public Context doInvoke(Context context);

    public Context doInvoke(Context context, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_doInvoke(Context context);

    public Ice.AsyncResult begin_doInvoke(Context context, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_doInvoke(Context context, Ice.Callback __cb);

    public Ice.AsyncResult begin_doInvoke(Context context, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_doInvoke(Context context, Callback_MessageService_doInvoke __cb);

    public Ice.AsyncResult begin_doInvoke(Context context, java.util.Map<String, String> __ctx, Callback_MessageService_doInvoke __cb);

    public Ice.AsyncResult begin_doInvoke(Context context, 
                                          IceInternal.Functional_GenericCallback1<Context> __responseCb, 
                                          IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_doInvoke(Context context, 
                                          IceInternal.Functional_GenericCallback1<Context> __responseCb, 
                                          IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                          IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_doInvoke(Context context, 
                                          java.util.Map<String, String> __ctx, 
                                          IceInternal.Functional_GenericCallback1<Context> __responseCb, 
                                          IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_doInvoke(Context context, 
                                          java.util.Map<String, String> __ctx, 
                                          IceInternal.Functional_GenericCallback1<Context> __responseCb, 
                                          IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                          IceInternal.Functional_BoolCallback __sentCb);

    public Context end_doInvoke(Ice.AsyncResult __result);
}
