// **********************************************************************
//
// Copyright (c) 2003-2018 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.5
//
// <auto-generated>
//
// Generated from file `Hello.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.rain.service;

public interface Hello extends Ice.Object,
                               _HelloOperations, _HelloOperationsNC
{
    public static final String ice_staticId = "::service::Hello";

    public static final long serialVersionUID = -157919102L;
}
